<?php

namespace BOR\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockPostRepository extends EntityRepository
{
}
