<?php

namespace BOR\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param string $keywords
     *
     * @return array
     */
    public function searchFind($keywords)
    {
        $qb = $this->createQueryBuilder('p');

        $qb = $this->searchByKeywords($qb, $keywords);

        $results = $qb->getQuery()->getResult();

        return $results;
    }

    /**
     * @param QueryBuilder $qb
     * @param string       $keywords
     *
     * @return QueryBuilder
     */
    public function searchByKeywords(QueryBuilder $qb, $keywords)
    {
        $qb->where('p.active = 1')
            ->andWhere('p.title LIKE :keywords')
            ->orWhere('p.content LIKE :keywords')
            ->setParameter('keywords', '%'.$keywords.'%');

        return $qb;
    }
}
