security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_EXPERT: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_EXPERT]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        api_open:
            pattern:   /api/mobile/open/.*
            anonymous: true
        api_mooc:
            pattern:   /api/mooc/user
            anonymous: true
        wsse_secured:
            pattern:   /api/mobile/.*
            stateless: true
            wsse:      true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /mon-profil
                #csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/blockAdvert, role: ROLE_ADMIN }
        - { path: ^/annonce/create, role: ROLE_USER }
        - { path: ^/article/create, role: ROLE_EXPERT }
        - { path: ^/article/edit, role: ROLE_EXPERT }
        - { path: ^/blockpost/, role: ROLE_USER }
        - { path: ^/mon-profil, role: ROLE_USER }
