services:
    wsse.security.authentication.provider:
        class:  BOR\ApiBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    wsse.security.authentication.listener:
        class:  BOR\ApiBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]
