<?php

namespace BOR\GamificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class LevelRepository extends EntityRepository
{
    /**
     * @param integer $pointExp
     *
     * @return mixed
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     *
     */
    public function findLevelWithExperience($pointExp)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->andWhere('s.experienceMin <= :pointExp')
            ->andWhere('s.experienceMax >= :pointExp')
            ->setParameter('pointExp', $pointExp);

        $result = $qb->getQuery()
                      ->getSingleResult();

        return $result;
    }

    /**
     * Renvoi la requête du niveau précédent ou suivant selon le signe signe : ["prev", "next"]
     *
     * @param integer   $level
     * @param string    $direction
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getPreviousOrNextLevel($level, $direction)
    {
        if ($direction == 'prev') {
            $level = $level -1;
        } else {
            $level = $level +1;
        }

        return $this->createQueryBuilder('s')
            ->andWhere('s.level = :level')
            ->setParameter('level', $level);
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     *
     */
    public function getLevelMax()
    {
        return $this->createQueryBuilder('s')
            ->select('s, MAX(s.level) AS max_level');
    }
}
