<?php

namespace BOR\GamificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QcmPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmPointRepository extends EntityRepository
{
}
