# src/BOR/UserBundle/Resources/config/services.yml
parameters:
    interactive_login_listener.class:
        BOR\UserBundle\EventListener\LoginListener

services:
    bor_user.registration.form.type:
        class: BOR\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bor_user_registration }

    bor_user.profile.form.type:
        class: BOR\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bor_user_profile }


    bor_user.listener.authentication:
        class: BOR\UserBundle\EventListener\AuthenticationListener
        arguments: ["@fos_user.security.login_manager", %fos_user.firewall_name%, "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    login_listener:
        class: %interactive_login_listener.class%
        arguments:
            userManager: "@fos_user.user_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }