<?php

namespace BOR\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllBySlideOrderAndActive()
    {
        return $this->findBy(array('active' => true), array('slideOrder' => 'ASC'));
    }
}
