<?php

namespace BOR\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockUserRepository extends EntityRepository
{
}
