<?php

namespace BOR\AdvertBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockAdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockAdvertRepository extends EntityRepository
{
}
